spring:
  application:
    name: ${SPRING_APP_NAME:Spring Security Leaning}
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false
    username: root
    password: password
  security:
    user:
      name: ${SECURITY_USERNAME:lvs}
      password: ${SECURITY_PASSWORD:123}

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
  level:
    spring:
      security: ${SPRING_SECURITY_LOGGING_LEVEL:TRACE}