spring:
  config:
    import: application_prod.yaml
  profiles:
    active:
      - prod
  application:
    name: ${SPRING_APP_NAME:Spring Security Leaning}
  datasource:
    url: jdbc:mysql://localhost:3306/eazybank?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: password #root
  security:
    user:
      name: ${SECURITY_USERNAME:lvs}
      password: ${SECURITY_PASSWORD:123}
  sql:
    init:
      mode: ALWAYS    #change it accordingly
      schema-locations: classpath:/sql/schema.sql
      data-locations: classpath:/sql/data.sql
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true


    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true


logging:
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
  level:
    spring:
      security: ${SPRING_SECURITY_LOGGING_LEVEL:TRACE}
server:
  servlet:
    session:
      timeout: ${SESSION_TIMEOUT:120s}